language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://conventic.pact.dius.com.au/
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "Xdbcvq8SpmiWzibiATVfDjG5qINVeuRalnmfsdpYVWCB5Q4Y59Ck5BdR1H8ThTAW7st7pCx87JWhGUwPo0f/dm/IiiNRw6YYjBYFmDYneippCJ7EeCDWSlAZ2WZVnWGQ15Ck2rA73vygmgtPWiubElSEENMlxl9zdEdIn7pbJVIEiOpPxxjVdsBmWeESQRNsyfXob1XrCstSoeuI2VOwMGjYfjI5BPjsMRcITuCsaw0WQazoFzE4yT5qQMiYodIQhoCiPH9Coj/8SfaKcGqz7C8Jgq3XrJM4feAA23dfXU4IeFqsquT80cSBMbauxhp18x5qoMSLL1T+sYgpwz62u7dXO+HM6z2r7bJjZBjc11MJ5H2Gw8KS/T4yMh+B1Z9wvBtshoiCPK07Gu8zm233RBA6QZ7YwXI47ITbx1DFvlfCiX4ww96Xvr2/8Biszbu92Jlaq1Ex6ovi7vm8N8vEXJBu0b2JHp32+NCncEwPP99lfshUgryIKiBx33AyvpZHp7GLBsNGJUWSrhjKYDB9WjJ1RfFNSQ2LukMFG8BrEhr4mrpUxFluVqyq9qwfiS/ERfkLkLrbFxXzKCxjs4W1tYXP5IHeVheTv6yEfxOh34T8QScIU/wUgxJydFAaGkZ65AuLXIaXWY1MMRL4TRE9A71Rcl+ioeVqfHeAy3rjuEw="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
